### ISSUE TITLE
No module named errors

### ISSUE THREAD

**Issue by azah** [x89/Shreddit#78]
```
Traceback (most recent call last):
  File "/usr/local/bin/shreddit", line 7, in <module>
    from shreddit.app import main
  File "/usr/local/lib/python2.7/dist-packages/shreddit/app.py", line 10, in <module>
    from shreddit.shredder import Shredder
  File "/usr/local/lib/python2.7/dist-packages/shreddit/shredder.py", line 12, in <module>
    from praw.errors import (InvalidUser, InvalidUserPass, RateLimitExceeded,
ImportError: No module named errors
```

**Comment by scott-hand** [comment]
Does my comment in [this issue](https://github.com/x89/Shreddit/issues/73) help?

**Comment by azah** [comment]
Nope, still getting the same error even after removing praw version and force reinstalling/upgrading.

**Comment by azah** [comment]
Actually, upon doing your advice for the 4th time, shreddit now works.

However, `get_secret.py` fails:
```
The OAuth app config parameters client_id, client_secret and redirect_url must be specified to use this function.
```

This is my praw.ini:
```ini
[DEFAULT]

oauth_client_id=xxx
oauth_client_secret=yyy
oauth_redirect_uri=zzz
```

**Comment by azah** [comment]
Nevermind. Running things multiple times magically fixes them.

**Comment by blhack** [comment]
Having this same issue.  Scott's recommendation does not seem to solve things.

**Comment by azah** [comment]
I just completely nuked the installation (`pip uninstall -r requirements.txt`), and on the third time reinstalling everything, it worked. No clue why.

**Comment by scott-hand** [comment]
@blhack Sorry to hear it's being such a problem. Have you tried just doing a pip uninstall of shreddit and doing the pip install from PyPI?

Ultimately, I have to wonder if this is a bunch of PRAW v4 changes that break backwards compatibility, and one of the immediate goals will be to switch to PRAW v4. Usually I don't upgrade things so quickly but (a) PRAW v3 is already spewing nasty messages about immediate deprecation and (b) I hate PRAW v3, and since v4 seems to be drinking whatever kool-aid the boto3 devs were, it might end up being a tolerable library as well.

**Comment by blhack** [comment]
@scott-hand explicitly requiring praw==3.0 in requirements.txt seems to have solved it.

**Comment by skath** [comment]
> @scott-hand explicitly requiring praw==3.0 in requirements.txt seems to have solved it.

3.0 is a bit far back to reach. Looks like anything lower than 4.0.0 does the trick. 

I submitted pull request #79 with the change that worked for me.

**Comment by scott-hand** [comment]
@skath Looks reasonable. I'll go ahead and merge it.

@x89 PRAW is going to be a real PITA now given the complete overhaul it did in PRAW V4 as well as its deprecation nasty messages every time it's run. The problem is that V4 mandates OAuth is used, even though it's much easier to set up from what I've seen. Do you think it's worth upgrading, or do you think people will balk at the OAuth requirement? I was thinking about maybe adding an interactive setup script or something to help guide people through the steps.

**Comment by x89** [comment]
Lots of ways to do this re: oauth but yes it's going to be a pain
regardless. And I don't think relying on praw <4 is a solution. There used
to be a "we're deprecating password logins" warning for months and months
and they never did.

It's why I've been considering a web app but the two dislikes I have there
are that it takes the uniquely full control away from the users and
secondly I'm not a good designer. I love my servers and backend development
but CSS gives me nightmares!

But OAuth, since it seems it's going to really be a requirement in the
future needs a very user friendly setup script/executable. Especially on
Windows and OSx.

Have you looked at praw 4 with oauth? I take it those change should be
fairly trivial? I'll have a look later and create a praw4 branch if its not
working.
