### ISSUE TITLE
Crash on line 74 of shredder.py: _connect() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by e1hd983** [x89/Shreddit#85]
Hello again. Shreddit working for me now, but crashes after 1009 items. 

INFO:shreddit:Finished deleting 1009 items. 
INFO:shreddit:Waiting 10 seconds and continuing...
Traceback (most recent call last):
  File "/Users/myusername/anaconda/envs/shreddit2/bin/shreddit", line 11, in <module>
    load_entry_point('shreddit==6.0.3', 'console_scripts', 'shreddit')()
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.3-py3.5.egg/shreddit/app.py", line 45, in main
  File "/Users/myusername/anaconda/envs/shreddit2/lib/python3.5/site-packages/shreddit-6.0.3-py3.5.egg/shreddit/shredder.py", line 74, in shred
TypeError: _connect() takes 2 positional arguments but 4 were given

As far as I can tell, the _connect() call on line 74 of shredder.py is ever so slightly different than the _connect() call on line 27. The call on line 27 just passes in the "user" argument, whereas line 74 passes in "None", "username", and "password". Could the "username" "password" be a leftover from before the update requiring a key for all connections to reddit API?

**Comment by scott-hand** [comment]
Good catch. Sorry for all the regressions, I'm going to work on using my commenting bot to rig up some test cases for these rare situations eventually.

I submitted a patch but haven't uploaded it to PyPI, so you'll have to clone and do `python setup.py install`.

I'll have my comment bot post a few thousand comments to delete so that I can test if you have <1000 comments left.

**Comment by e1hd983** [comment]
I think this is fixed. It hasn't come up again since applying the patch.
